### PR TITLE
feat: added config option prefixEntityNamesWithCarName

### PR DESCRIPTION
**Pull request by CyberDNS**
Hi @wubbl0rz,

Here is a suggestion how the functionality in #31 could be implemented.
Unfortunately the formatting of my Visual Studio changed the whole indentation, can you provide me the used settings so that I can correct the issue.

Mainly I added a new configuration option (bool) to AppConfig and config.yml, then pushed the value down to the HaEntity class constructor to prefix the name of the entity with the device/car name.

Implements #31.

Best regards,
@CyberDNS

### CODE REVIEW

**Comment by wubbl0rz** [comment]
thx for the pull requests. i cannot exactly see whats changed because all files have been reformatted. :thinking: 
files should have 2 space indentation or better not reformat whole file at all :smile:

**Comment by CyberDNS** [comment]
I will fix the indentation and then do a rebase and force push on this pull request to have a clean commit history.

**Comment by CyberDNS** [comment]
That was quite wearing. Had to redo the code in HomeAssistant.cs, but now it is ok.

I have already changed the changelogs but did not put a version number.

**Comment by nicjansma** [comment]
@CyberDNS or @wubbl0rz any chance this will be picked up again soon?

Would love to have this to differentiate things e.g. it makes me nervous the switches are very generically named like `switch.doorlock`

**Comment by CyberDNS** [comment]
> @CyberDNS any chance this will be picked up again soon?
> 
> Would love to have this to differentiate things e.g. it makes me nervous the switches are very generically named like `switch.doorlock`

Good question, we should ask @wubbl0rz?

**Comment by CyberDNS** [comment]
As I have no interest anymore in this repository, I will unsubscribe from this pull request thread. @wubbl0rz feel free to close or not this pull request and handle the comments from other users.

**Pull request closed without merging**
